theme: minima
markdown: CommonMarkGhPages
title: sinsukehlab's homepage
author:
  name: sinsukehlab
  email: 94058150+sinsukehlab@users.noreply.github.com
description: &copy; 2023 Shinsuke Higashiyama

plugins:
  - jemoji
