theme: minima
markdown: kramdown

title: sinsukehlab's homepage

author: Shinsuke Higashiyama
email: CRISPR-Cas@chemist.com
github_username: sinsukehlab
rss: rss

description: "\xA9 2023 Shinsuke Higashiyama"

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
