theme: minima
markdown: CommonMarkGhPages

title: sinsukehlab's homepage

author: Shinsuke Higashiyama
github_username: sinsukehlab
rss: rss

description: "\xA9 2023 Shinsuke Higashiyama"

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
